// Writes SkyMapUITests/WalkFixture.swift: a route's drawn line as GPS
// waypoints, plus where each building starts along it, computed by the app's
// own router and routeLine. Re-run after a data refresh changes the network:
//   node ios/UITests/make-walk.mjs "Target Center" "IDS Center"
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "../..");
const { SkywayRouter, buildingExitPoint } = await import(join(ROOT, "src/router.ts"));
const { routeLine } = await import(join(ROOT, "src/route-geometry.ts"));
const data = JSON.parse(readFileSync(join(ROOT, "public/data/skymap-data.json"), "utf8"));
const [fromName, toName] = process.argv.slice(2);
const from = data.buildings.find((b) => b.name === fromName);
const to = data.buildings.find((b) => b.name === toName);
if (!from || !to) throw new Error(`unknown building: ${!from ? fromName : toName}`);

// Hours-blind, so the fixture doesn't depend on when it was generated; the
// test walks at midday, when every building on this route is open.
const route = new SkywayRouter(data).route(from.id, to.id, null);
const s = route.steps;
// The same endpoints map.ts draws for a building-to-building route.
const fromCoord = buildingExitPoint(from, s[1].legGeometry?.[0] ?? [s[1].building.lon, s[1].building.lat]);
const toCoord = buildingExitPoint(to, s.at(-1).legGeometry?.at(-1) ?? [from.lon, from.lat]);
const { coords, stepStarts } = routeLine(route, fromCoord, toCoord, data.indoorLinks);

const swift = `// Generated by make-walk.mjs — do not edit by hand.
import CoreLocation

enum WalkFixture {
  static let from = ${JSON.stringify(fromName)}
  static let to = ${JSON.stringify(toName)}
  static let buildings: [String] = [${s.map((x) => JSON.stringify(x.building.name)).join(", ")}]
  /// Metres along the drawn line where each building begins.
  static let stepStarts: [Double] = [${stepStarts.map((m) => m.toFixed(1)).join(", ")}]
  static let waypoints: [CLLocationCoordinate2D] = [
${coords.map(([lon, lat]) => `    CLLocationCoordinate2D(latitude: ${lat}, longitude: ${lon}),`).join("\n")}
  ]
}
`;
writeFileSync(join(HERE, "SkyMapUITests/WalkFixture.swift"), swift);
console.log(`${fromName} -> ${toName}: ${s.length} buildings, starts ${stepStarts.map(Math.round).join(", ")} m`);
