// Writes SkyMapUITests/WalkFixture.swift: a route's drawn line as GPS
// waypoints, plus where each building starts along it, computed by the app's
// own router and routeLine. Re-run after a data refresh changes the network:
//   node ios/UITests/make-walk.mjs "Target Plaza" "LaSalle Plaza"
// The test runs at whatever time it is, and the app routes by building
// hours, so the route must come out the same at every hour of the week;
// this refuses to write a fixture for one that doesn't.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "../..");
const { SkywayRouter, buildingExitPoint } = await import(join(ROOT, "src/router.ts"));
const { routeLine } = await import(join(ROOT, "src/route-geometry.ts"));
const data = JSON.parse(readFileSync(join(ROOT, "public/data/skymap-data.json"), "utf8"));
const [fromName, toName] = process.argv.slice(2);
const from = data.buildings.find((b) => b.name === fromName);
const to = data.buildings.find((b) => b.name === toName);
if (!from || !to) throw new Error(`unknown building: ${!from ? fromName : toName}`);

const router = new SkywayRouter(data);
const route = router.route(from.id, to.id, null);
const ids = (r) => r?.steps.map((x) => x.building.id).join(">");
for (let day = 0; day < 7; day++) {
  for (let hour = 0; hour < 24; hour++) {
    const when = new Date(2026, 9, 4 + day, hour, 30); // Sun Oct 4 2026 onward
    const r = router.route(from.id, to.id, when);
    if (ids(r) !== ids(route) || r.ignoredClosures) {
      throw new Error(`route changes with building hours (${when.toString().slice(0, 21)}); pick buildings open all week`);
    }
  }
}
const s = route.steps;
// The same endpoints map.ts draws for a building-to-building route.
const fromCoord = buildingExitPoint(from, s[1].legGeometry?.[0] ?? [s[1].building.lon, s[1].building.lat]);
const toCoord = buildingExitPoint(to, s.at(-1).legGeometry?.at(-1) ?? [from.lon, from.lat]);
const { coords, stepStarts } = routeLine(route, fromCoord, toCoord, data.indoorLinks);

const swift = `// Generated by make-walk.mjs — do not edit by hand.
import CoreLocation

enum WalkFixture {
  static let from = ${JSON.stringify(fromName)}
  static let to = ${JSON.stringify(toName)}
  static let buildings: [String] = [${s.map((x) => JSON.stringify(x.building.name)).join(", ")}]
  /// Metres along the drawn line where each building begins.
  static let stepStarts: [Double] = [${stepStarts.map((m) => m.toFixed(1)).join(", ")}]
  static let waypoints: [CLLocationCoordinate2D] = [
${coords.map(([lon, lat]) => `    CLLocationCoordinate2D(latitude: ${lat}, longitude: ${lon}),`).join("\n")}
  ]
}
`;
writeFileSync(join(HERE, "SkyMapUITests/WalkFixture.swift"), swift);
console.log(`${fromName} -> ${toName}: ${s.length} buildings, starts ${stepStarts.map(Math.round).join(", ")} m`);
