// Generated by make-walk.mjs — do not edit by hand.
import CoreLocation

enum WalkFixture {
  static let from = "Target Center"
  static let to = "IDS Center"
  static let buildings: [String] = ["Target Center", "Mayo Clinic Square", "Minneapolis Marriott City Center", "The Royal Sonesta Minneapolis Downtown", "IDS Center"]
  /// Metres along the drawn line where each building begins.
  static let stepStarts: [Double] = [0.0, 46.3, 193.5, 314.5, 446.7]
  static let waypoints: [CLLocationCoordinate2D] = [
    CLLocationCoordinate2D(latitude: 44.979437, longitude: -93.275261),
    CLLocationCoordinate2D(latitude: 44.979437, longitude: -93.275261),
    CLLocationCoordinate2D(latitude: 44.97915, longitude: -93.274834),
    CLLocationCoordinate2D(latitude: 44.979054, longitude: -93.274708),
    CLLocationCoordinate2D(latitude: 44.978902, longitude: -93.274708),
    CLLocationCoordinate2D(latitude: 44.978553, longitude: -93.274281),
    CLLocationCoordinate2D(latitude: 44.978351, longitude: -93.274009),
    CLLocationCoordinate2D(latitude: 44.978141, longitude: -93.273706),
    CLLocationCoordinate2D(latitude: 44.977422, longitude: -93.273094),
    CLLocationCoordinate2D(latitude: 44.977244, longitude: -93.273339),
    CLLocationCoordinate2D(latitude: 44.977136, longitude: -93.273439),
    CLLocationCoordinate2D(latitude: 44.976887, longitude: -93.273634),
    CLLocationCoordinate2D(latitude: 44.97661, longitude: -93.272956),
    CLLocationCoordinate2D(latitude: 44.976577, longitude: -93.272982),
    CLLocationCoordinate2D(latitude: 44.976465, longitude: -93.272775),
    CLLocationCoordinate2D(latitude: 44.976465, longitude: -93.272775),
  ]
}
